### ISSUE TITLE
`break` throws NoMethodError on master

### ISSUE THREAD

**Issue by caius** [deivid-rodriguez/pry-byebug#32]
I just installed pry-byebug from master (17f9bc7b0b8a1666667b9dd574d8ae3241e21cda specifically) and found the following:

```
$ pry
2.1.2 (main):0 > require "pry-byebug"
=> false
2.1.2 (main):0 > class Fred; def foo; end; end
=> :foo
2.1.2 (main):0 > break Fred#foo
NoMethodError: undefined method `<<' for nil:NilClass
from /Users/caius/.gem/ruby/2.1.2/gems/byebug-3.2.0/lib/byebug.rb:44:in `add_breakpoint'
```

The same code works fine on v1.3.3 installed from rubygems.
